# Generated by Django 6.0.6 on 2026-06-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museo',
            options={},
        ),
    ]
