# Generated by Django 6.0.6 on 2026-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_alter_museo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibicion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guiamuseo',
            options={},
        ),
    ]
